`timescale 1ns / 1ps

module tb_image_divider;

    // Parameter Definitions
    parameter DATA_WIDTH = 32;
    parameter IMG_SIZE = 658*877; // 64 * 64, please ensure consistency with the quantity generated by Python
    
    // File handle
    integer file_out;
    
    // Signal Definitions
    // Note: In combinational logic testing, although the divider does not need a clock,
    // the Testbench usually still needs a clock (or delays) to control the rhythm of reading the array.
    reg [DATA_WIDTH-1:0] data_in_a;
    reg [DATA_WIDTH-1:0] data_in_b;
    wire [DATA_WIDTH-1:0] data_out;
    
    // Memory arrays, used to simulate file reading
    reg [DATA_WIDTH-1:0] mem_img1 [0:IMG_SIZE-1];
    reg [DATA_WIDTH-1:0] mem_img2 [0:IMG_SIZE-1];
    
    integer i;

    // -----------------------------------------------------------
    // Instantiate combinational logic floating-point divider
    // -----------------------------------------------------------
    approx_l_div_fp32 u_div (
        .a(data_in_b),
        .b(data_in_a),
        .q(data_out)
    );
    
    // Main test flow
    initial begin
        // 1. Initialization
        data_in_a = 0;
        data_in_b = 0;
        
        // 2. Read hex files generated by Python into memory arrays
        // Please ensure these two files are in the simulation directory
        $readmemh("C:\\Users\\Razer\\Desktop\\DATE_divider\\img1_hex.txt", mem_img1);
        $readmemh("C:\\Users\\Razer\\Desktop\\DATE_divider\\img2_hex.txt", mem_img2);
        
        // Open output file
        file_out = $fopen("C:\\Users\\Razer\\Desktop\\DATE_divider\\result_hex.txt", "w");
        if (file_out == 0) begin
            $display("Error: Could not open output file.");
            $finish;
        end

        // Wait a bit for the system to stabilize
        #100;
        
        $display("Simulation Start: Processing %d pixels (Combinational)...", IMG_SIZE);

        // 3. Loop to process each pixel
        for (i = 0; i < IMG_SIZE; i = i + 1) begin
            
            // A. Apply inputs
            data_in_a = mem_img1[i];
            data_in_b = mem_img2[i];
            
            // B. Wait for combinational logic calculation to complete
            // In actual hardware this is gate delay; in simulation we need to give some time for signal propagation
            // Also to make the waveform look spaced out
            #10; 
            
            // C. Write result to file
            // At this point data_out is already the calculated result
            $fdisplay(file_out, "%h", data_out);
            
            // Print progress
            if (i % 100 == 0) $display("Processed pixel %d, Result: %h", i, data_out);
        end

        // 4. End
        $fclose(file_out);
        $display("Simulation Finished. Results saved to result_hex.txt");
        $finish;
    end

endmodule